apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\danil\Documents\kompose\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: clickservice
  name: clickservice
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: clickservice
status:
  loadBalancer: {}
