apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\danil\Documents\kompose\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: impressionservice
  name: impressionservice
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: impressionservice
    spec:
      containers:
      - image: localhost:5000/impressionservice
        name: impressionservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
