apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\danil\Documents\kompose\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: impressionservice
  name: impressionservice
spec:
  type: NodePort
  ports:
  - name: "9020"
    port: 9020
    targetPort: 8080
  selector:
    io.kompose.service: impressionservice
status:
  loadBalancer: {}
